@MyFirstApi_HostAddress = http://localhost:5065

GET {{MyFirstApi_HostAddress}}/api/products/-1
Accept: application/json

###

POST {{MyFirstApi_HostAddress}}/api/products
Content-Type: application/json

{
  "id": 1,
  "name": "Apple Juice",
  "price": 3.99
}

###

PUT {{MyFirstApi_HostAddress}}/api/products/1
Content-Type: application/json

{
  "name": "Orange Juice",
  "price": 4.95
}

###

GET {{MyFirstApi_HostAddress}}/minimal/10
Content-Type: application/json
###

GET {{MyFirstApi_HostAddress}}/minimal/10/John
Content-Type: application/json  
###

GET {{MyFirstApi_HostAddress}}/minimal
Content-Type: application/json
###

GET {{MyFirstApi_HostAddress}}/minimal/file/images/photo.jpg
Content-Type: application/json
###

GET {{MyFirstApi_HostAddress}}/minimal/store/electronic/laptop/101?inStock=true
Content-Type: application/json
###